language: android
android:
  components:
  - platform-tools
  - android-22
  - build-tools-22.0.1
  - extra

jdk: oraclejdk7

notifications:
 email: false

before_install:
 - sudo apt-get update -qq

script:
 - ./gradlew clean build
 
